In [1]:
import pandas as pd
import numpy as np
import duckdb
import sklearn
import xgboost
import lightgbm

print("Entorno correcto")

Entorno correcto

In [27]:
import duckdb

con = duckdb.connect("../data/raw/transfermarkt/transfermarkt-datasets.duckdb")

con.sql("SHOW TABLES")

IOException: IO Error: Cannot open file "C:\Users\salit\OneDrive\Documentos\GitHub\DS-Online_willwalker7\football-recruitment-analytics\data\raw\transfermarkt\transfermarkt-datasets.duckdb": El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

File is already open in
C:\Users\salit\AppData\Local\Programs\Python\Python313\python.exe (PID 5020)

In [6]:
con.sql("DESCRIBE players")

┌──────────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│             column_name              │ column_type │  null   │   key   │ default │  extra  │
│               varchar                │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ player_id                            │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ first_name                           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ last_name                            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ name                                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ last_season                          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_id                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_code                          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ country_of_birth                     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ city_of_birth                        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ country_of_citizenship               │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│     ·                                │    ·        │  ·      │  ·      │  ·      │  ·      │
│     ·                                │    ·        │  ·      │  ·      │  ·      │  ·      │
│     ·                                │    ·        │  ·      │  ·      │  ·      │  ·      │
│ agent_name                           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ image_url                            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ international_caps                   │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ international_goals                  │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_national_team_id             │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ url                                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_domestic_competition_id │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_name                    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ market_value_in_eur                  │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ highest_market_value_in_eur          │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
└──────────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  26 rows (20 shown)                                                               6 columns

In [9]:
con.sql("DESCRIBE appearances")

┌────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│      column_name       │ column_type │  null   │   key   │ default │  extra  │
│        varchar         │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ appearance_id          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ game_id                │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_id              │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_club_id         │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_current_club_id │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ date                   │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ player_name            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ competition_id         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ yellow_cards           │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ red_cards              │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ goals                  │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ assists                │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ minutes_played         │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  13 rows                                                            6 columns

In [10]:
con.sql("DESCRIBE player_valuations")

┌─────────────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│             column_name             │ column_type │  null   │   key   │ default │  extra  │
│               varchar               │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ player_id                           │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ date                                │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
│ market_value_in_eur                 │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_name                   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ current_club_id                     │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ player_club_domestic_competition_id │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [11]:
con.sql("DESCRIBE transfers")

┌─────────────────────┬───────────────┬─────────┬─────────┬─────────┬─────────┐
│     column_name     │  column_type  │  null   │   key   │ default │  extra  │
│       varchar       │    varchar    │ varchar │ varchar │ varchar │ varchar │
├─────────────────────┼───────────────┼─────────┼─────────┼─────────┼─────────┤
│ player_id           │ INTEGER       │ YES     │ NULL    │ NULL    │ NULL    │
│ transfer_date       │ DATE          │ YES     │ NULL    │ NULL    │ NULL    │
│ transfer_season     │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
│ from_club_id        │ INTEGER       │ YES     │ NULL    │ NULL    │ NULL    │
│ to_club_id          │ INTEGER       │ YES     │ NULL    │ NULL    │ NULL    │
│ from_club_name      │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
│ to_club_name        │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
│ transfer_fee        │ DECIMAL(18,3) │ YES     │ NULL    │ NULL    │ NULL    │
│ market_value_in_eur │ DECIMAL(18,3) │ YES     │ NULL    │ NULL    │ NULL    │
│ player_name         │ VARCHAR       │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────────────┴───────────────┴─────────┴─────────┴─────────┴─────────┘
  10 rows                                                           6 columns

In [13]:
con.sql("SELECT * FROM players LIMIT 5")

┌───────────┬────────────┬──────────────┬────────────────────┬─────────────┬─────────────────┬────────────────────┬────────────────────┬───────────────┬────────────────────────┬─────────────────────┬────────────────┬────────────┬─────────┬──────────────┬──────────────────────────┬──────────────────────┬───────────────────────────────────────────────────────────────────────────────┬────────────────────┬─────────────────────┬──────────────────────────┬──────────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬─────────────────────────────────────────────────────────┬─────────────────────┬─────────────────────────────┐
│ player_id │ first_name │  last_name   │        name        │ last_season │ current_club_id │    player_code     │  country_of_birth  │ city_of_birth │ country_of_citizenship │    date_of_birth    │  sub_position  │  position  │  foot   │ height_in_cm │ contract_expiration_date │      agent_name      │                                   image_url                                   │ international_caps │ international_goals │ current_national_team_id │                                 url                                  │ current_club_domestic_competition_id │                    current_club_name                    │ market_value_in_eur │ highest_market_value_in_eur │
│   int32   │  varchar   │   varchar    │      varchar       │   varchar   │     varchar     │      varchar       │      varchar       │    varchar    │        varchar         │      timestamp      │    varchar     │  varchar   │ varchar │    int32     │        timestamp         │       varchar        │                                    varchar                                    │       int32        │        int32        │         varchar          │                               varchar                                │               varchar                │                         varchar                         │        int32        │            int32            │
├───────────┼────────────┼──────────────┼────────────────────┼─────────────┼─────────────────┼────────────────────┼────────────────────┼───────────────┼────────────────────────┼─────────────────────┼────────────────┼────────────┼─────────┼──────────────┼──────────────────────────┼──────────────────────┼───────────────────────────────────────────────────────────────────────────────┼────────────────────┼─────────────────────┼──────────────────────────┼──────────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼─────────────────────────────────────────────────────────┼─────────────────────┼─────────────────────────────┤
│        10 │ Miroslav   │ Klose        │ Miroslav Klose     │ 2015        │ 398             │ miroslav-klose     │ Poland             │ Opole         │ Germany                │ 1978-06-09 00:00:00 │ Centre-Forward │ Attack     │ right   │          184 │ NULL                     │ ASBW Sport Marketing │ https://img.a.transfermarkt.technology/portrait/header/10-1448468291.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/miroslav-klose/profil/spieler/10     │ IT1                                  │ Società Sportiva Lazio S.p.A.                           │             1000000 │                    30000000 │
│        26 │ Roman      │ Weidenfeller │ Roman Weidenfeller │ 2017        │ 16              │ roman-weidenfeller │ Germany            │ Diez          │ Germany                │ 1980-08-06 00:00:00 │ Goalkeeper     │ Goalkeeper │ left    │          190 │ NULL                     │ Neubauer 13 GmbH     │ https://img.a.transfermarkt.technology/portrait/header/26-1502448725.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/roman-weidenfeller/profil/spieler/26 │ L1                                   │ Borussia Dortmund                                       │              750000 │                     8000000 │
│        65 │ Dimitar    │ Berbatov     │ Dimitar Berbatov   │ 2015        │ 1091            │ dimitar-berbatov   │ Bulgaria           │ Blagoevgrad   │ Bulgaria               │ 1981-01-30 00:00:00 │ Centre-Forward │ Attack     │ NULL    │         NULL │ NULL                     │ CSKA-AS-23 Ltd.      │ https://img.a.transfermarkt.technology/portrait/header/65-1683670068.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/dimitar-berbatov/profil/spieler/65   │ GR1                                  │ Panthessalonikios Athlitikos Omilos Konstantinoupoliton │             1000000 │                    34500000 │
│        77 │ NULL       │ Lúcio        │ Lúcio              │ 2012        │ 506             │ lucio              │ Brazil             │ Brasília      │ Brazil                 │ 1978-05-08 00:00:00 │ Centre-Back    │ Defender   │ NULL    │         NULL │ NULL                     │ NULL                 │ https://img.a.transfermarkt.technology/portrait/header/77-1458201664.jpg?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/lucio/profil/spieler/77              │ IT1                                  │ Juventus FC                                             │              200000 │                    24500000 │
│        80 │ Tom        │ Starke       │ Tom Starke         │ 2017        │ 27              │ tom-starke         │ East Germany (GDR) │ Freital       │ Germany                │ 1981-03-18 00:00:00 │ Goalkeeper     │ Goalkeeper │ right   │          194 │ NULL                     │ IFM                  │ https://img.a.transfermarkt.technology/portrait/header/80-1471439914.JPG?lm=1 │               NULL │                NULL │ NULL                     │ https://www.transfermarkt.co.uk/tom-starke/profil/spieler/80         │ L1                                   │ Bayern Munich                                           │              100000 │                     3000000 │
└───────────┴────────────┴──────────────┴────────────────────┴─────────────┴─────────────────┴────────────────────┴────────────────────┴───────────────┴────────────────────────┴─────────────────────┴────────────────┴────────────┴─────────┴──────────────┴──────────────────────────┴──────────────────────┴───────────────────────────────────────────────────────────────────────────────┴────────────────────┴─────────────────────┴──────────────────────────┴──────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────────────────────────────────────────────────────┴─────────────────────┴─────────────────────────────┘

In [20]:
con.sql("SELECT last_name FROM players WHERE last_season = '2025'")

┌────────────────────────┐
│       last_name        │
│        varchar         │
├────────────────────────┤
│ Guerrero               │
│ Milner                 │
│ Tsokanis               │
│ Hofmann                │
│ García                 │
│ Cristiano Ronaldo      │
│ Luiz Gustavo           │
│ Funes Mori             │
│ Carole                 │
│ Banega                 │
│   ·                    │
│   ·                    │
│   ·                    │
│ Banks                  │
│ Torres                 │
│ Marchiori              │
│ Lepasa                 │
│ Sepúlveda              │
│ Martel                 │
│ Moreno                 │
│ Ould-Chikh             │
│ de Lucas               │
│ Teles                  │
└────────────────────────┘
          ? rows
  (>9999 rows, 20 shown)

In [21]:
con.sql("""
SELECT 
    last_season,
    COUNT(*) AS players
FROM players
GROUP BY last_season
ORDER BY last_season DESC
""")

┌─────────────┬─────────┐
│ last_season │ players │
│   varchar   │  int64  │
├─────────────┼─────────┤
│ 2025        │   22292 │
│ 2024        │    6075 │
│ 2023        │    2092 │
│ 2022        │    1877 │
│ 2021        │    1817 │
│ 2020        │    1843 │
│ 2019        │    1566 │
│ 2018        │    2065 │
│ 2017        │    1661 │
│ 2016        │    1831 │
│ 2015        │    1651 │
│ 2014        │    1660 │
│ 2013        │    2061 │
│ 2012        │    1658 │
└─────────────┴─────────┘
  14 rows     2 columns

In [22]:
con.sql("""
SELECT 
    MIN(transfer_date) AS first_transfer,
    MAX(transfer_date) AS last_transfer,
    COUNT(*) AS total_transfers
FROM transfers
""")

┌────────────────┬───────────────┬─────────────────┐
│ first_transfer │ last_transfer │ total_transfers │
│      date      │     date      │      int64      │
├────────────────┼───────────────┼─────────────────┤
│ 1993-07-01     │ 2030-06-30    │          175165 │
└────────────────┴───────────────┴─────────────────┘

In [23]:
con.sql("""
SELECT 
    MIN(date) AS first_valuation,
    MAX(date) AS last_valuation,
    COUNT(*) AS total_valuations
FROM player_valuations
""")

┌─────────────────┬────────────────┬──────────────────┐
│ first_valuation │ last_valuation │ total_valuations │
│      date       │      date      │      int64       │
├─────────────────┼────────────────┼──────────────────┤
│ 2000-01-20      │ 2026-06-12     │           656301 │
└─────────────────┴────────────────┴──────────────────┘

In [26]:
con.sql("""
SELECT *
FROM transfers
WHERE transfer_date >= '2028-01-01'
ORDER BY transfer_date
LIMIT 20
""")

┌───────────┬───────────────┬─────────────────┬──────────────┬────────────┬─────────────────┬──────────────┬───────────────┬─────────────────────┬───────────────────┐
│ player_id │ transfer_date │ transfer_season │ from_club_id │ to_club_id │ from_club_name  │ to_club_name │ transfer_fee  │ market_value_in_eur │    player_name    │
│   int32   │     date      │     varchar     │    int32     │   int32    │     varchar     │   varchar    │ decimal(18,3) │    decimal(18,3)    │      varchar      │
├───────────┼───────────────┼─────────────────┼──────────────┼────────────┼─────────────────┼──────────────┼───────────────┼─────────────────────┼───────────────────┤
│    645842 │ 2028-02-02    │ 27/28           │         6505 │      19684 │ Gimcheon Sangmu │ Jeju SK      │         0.000 │          150000.000 │ Chan-gi An        │
│    677470 │ 2028-02-02    │ 27/28           │         6505 │       3535 │ Gimcheon Sangmu │ Ulsan HD     │         0.000 │          400000.000 │ Yool Heo          │
│    709155 │ 2028-02-02    │ 27/28           │         6505 │      19684 │ Gimcheon Sangmu │ Jeju SK      │         0.000 │          325000.000 │ Jae-hyeok Oh      │
│    728133 │ 2028-02-02    │ 27/28           │         6505 │      35759 │ Gimcheon Sangmu │ Bucheon FC   │         0.000 │          175000.000 │ Sang-hyeok Lee    │
│    730364 │ 2028-02-02    │ 27/28           │         6505 │      38898 │ Gimcheon Sangmu │ FC Anyang    │         0.000 │          150000.000 │ Gyu-hyeon Choe    │
│    746780 │ 2028-02-02    │ 27/28           │         6505 │       2996 │ Gimcheon Sangmu │ Incheon Utd. │         0.000 │          125000.000 │ Young-hun Kang    │
│    755355 │ 2028-02-02    │ 27/28           │         6505 │      30925 │ Gimcheon Sangmu │ Gwangju FC   │         0.000 │          350000.000 │ Jin-ho Kim        │
│    862094 │ 2028-02-02    │ 27/28           │         6505 │      21459 │ Gimcheon Sangmu │ Gangwon FC   │         0.000 │          400000.000 │ Jun-seok Song     │
│    929007 │ 2028-02-02    │ 27/28           │         6505 │      19684 │ Gimcheon Sangmu │ Jeju SK      │         0.000 │          350000.000 │ Jun-ha Kim        │
│    467994 │ 2030-06-30    │ 25/26           │         5621 │        749 │ Reggiana        │ FC Empoli    │         0.000 │          700000.000 │ Luca Belardinelli │
└───────────┴───────────────┴─────────────────┴──────────────┴────────────┴─────────────────┴──────────────┴───────────────┴─────────────────────┴───────────────────┘
  10 rows                                                                                                                                                 10 columns

In [28]:
import pandas as pd

path = "../data/raw/fbref_2025-2026/players_data-2025_2026.csv"

df_fbref = pd.read_csv(path)

df_fbref.shape

(2839, 102)

In [29]:
df_fbref.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,24.0,2000.0,37,30,...,3,0,0,20,51,5,37,17,27,0
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,15.0,2009.0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,3,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,3,2,...,0,0,0,3,1,0,3,2,4,0
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,19.0,2006.0,22,4,...,0,0,0,7,3,2,30,3,3,0
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,25.0,1999.0,8,1,...,1,0,0,3,0,0,1,2,1,0

In [31]:
cols = df_fbref.columns.tolist()
for col in cols:
    print(col)

Rk
Player
Nation
Pos
Squad
Comp
Age
Born
MP
Starts
Min
90s
Gls
Ast
G+A
G-PK
PK
PKatt
CrdY
CrdR
G+A-PK
Rk_stats_keeper
Nation_stats_keeper
Pos_stats_keeper
Comp_stats_keeper
Age_stats_keeper
Born_stats_keeper
MP_stats_keeper
Starts_stats_keeper
Min_stats_keeper
90s_stats_keeper
GA
GA90
SoTA
Saves
Save%
W
D
L
CS
CS%
PKatt_stats_keeper
PKA
PKsv
PKm
Rk_stats_shooting
Nation_stats_shooting
Pos_stats_shooting
Comp_stats_shooting
Age_stats_shooting
Born_stats_shooting
90s_stats_shooting
Gls_stats_shooting
Sh
SoT
SoT%
Sh/90
SoT/90
G/Sh
G/SoT
PK_stats_shooting
PKatt_stats_shooting
Rk_stats_playing_time
Nation_stats_playing_time
Pos_stats_playing_time
Comp_stats_playing_time
Age_stats_playing_time
Born_stats_playing_time
MP_stats_playing_time
Min_stats_playing_time
Mn/MP
Min%
90s_stats_playing_time
Starts_stats_playing_time
Mn/Start
Compl
Subs
Mn/Sub
unSub
PPM
onG
onGA
+/-
+/-90
On-Off
Rk_stats_misc
Nation_stats_misc
Pos_stats_misc
Comp_stats_misc
Age_stats_misc
Born_stats_misc
90s_stats_misc
CrdY_stats_misc
CrdR_stats_misc
2CrdY
Fls
Fld
Off
Crs
Int
TklW
OG

In [33]:
df_fbref.info()

<class 'pandas.DataFrame'>
RangeIndex: 2839 entries, 0 to 2838
Columns: 102 entries, Rk to OG
dtypes: float64(45), int64(40), str(17)
memory usage: 2.2 MB

In [42]:
nan_dict = {}

for col in cols:
    nan_dict[col] = len(df_fbref[df_fbref[col].isna()])

nan_dict

{'Rk': 0,
 'Player': 0,
 'Nation': 3,
 'Pos': 0,
 'Squad': 0,
 'Comp': 0,
 'Age': 2,
 'Born': 2,
 'MP': 0,
 'Starts': 0,
 'Min': 0,
 '90s': 0,
 'Gls': 0,
 'Ast': 0,
 'G+A': 0,
 'G-PK': 0,
 'PK': 0,
 'PKatt': 0,
 'CrdY': 0,
 'CrdR': 0,
 'G+A-PK': 0,
 'Rk_stats_keeper': 2645,
 'Nation_stats_keeper': 2645,
 'Pos_stats_keeper': 2645,
 'Comp_stats_keeper': 2645,
 'Age_stats_keeper': 2645,
 'Born_stats_keeper': 2645,
 'MP_stats_keeper': 2645,
 'Starts_stats_keeper': 2645,
 'Min_stats_keeper': 2645,
 '90s_stats_keeper': 2645,
 'GA': 2645,
 'GA90': 2645,
 'SoTA': 2645,
 'Saves': 2645,
 'Save%': 2649,
 'W': 2645,
 'D': 2645,
 'L': 2645,
 'CS': 2645,
 'CS%': 2651,
 'PKatt_stats_keeper': 2645,
 'PKA': 2645,
 'PKsv': 2645,
 'PKm': 2645,
 'Rk_stats_shooting': 0,
 'Nation_stats_shooting': 3,
 'Pos_stats_shooting': 0,
 'Comp_stats_shooting': 0,
 'Age_stats_shooting': 2,
 'Born_stats_shooting': 2,
 '90s_stats_shooting': 0,
 'Gls_stats_shooting': 0,
 'Sh': 0,
 'SoT': 0,
 'SoT%': 490,
 'Sh/90': 0,
 'SoT/90': 0,
 'G/Sh': 490,
 'G/SoT': 826,
 'PK_stats_shooting': 0,
 'PKatt_stats_shooting': 0,
 'Rk_stats_playing_time': 0,
 'Nation_stats_playing_time': 3,
 'Pos_stats_playing_time': 0,
 'Comp_stats_playing_time': 0,
 'Age_stats_playing_time': 2,
 'Born_stats_playing_time': 2,
 'MP_stats_playing_time': 0,
 'Min_stats_playing_time': 0,
 'Mn/MP': 0,
 'Min%': 0,
 '90s_stats_playing_time': 0,
 'Starts_stats_playing_time': 0,
 'Mn/Start': 362,
 'Compl': 0,
 'Subs': 0,
 'Mn/Sub': 377,
 'unSub': 0,
 'PPM': 0,
 'onG': 0,
 'onGA': 0,
 '+/-': 0,
 '+/-90': 0,
 'On-Off': 25,
 'Rk_stats_misc': 0,
 'Nation_stats_misc': 3,
 'Pos_stats_misc': 0,
 'Comp_stats_misc': 0,
 'Age_stats_misc': 2,
 'Born_stats_misc': 2,
 '90s_stats_misc': 0,
 'CrdY_stats_misc': 0,
 'CrdR_stats_misc': 0,
 '2CrdY': 0,
 'Fls': 0,
 'Fld': 0,
 'Off': 0,
 'Crs': 0,
 'Int': 0,
 'TklW': 0,
 'OG': 0}

In [43]:
import pandas as pd

path = "../venv/Lib/site-packages/data/unified_player_stats.csv"

df = pd.read_csv(path)

df.shape

C:\Users\salit\AppData\Local\Temp\ipykernel_5020\3348345512.py:5: DtypeWarning: Columns (0: pos) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

(22297, 149)

In [44]:
df.columns.tolist()

['understat_id',
 'player',
 'team',
 'pos',
 'games',
 'minutes',
 'goals',
 'assists',
 'shots',
 'key_passes',
 'yellow_cards',
 'red_cards',
 'npg',
 'league',
 'season',
 'xg',
 'xag',
 'npxg',
 'xg_chain',
 'xg_buildup',
 'ninety_s',
 'sofascore_id',
 'sofascore_team_id',
 'sofascore_rating',
 'sofascore_rating_total',
 'sofascore_rating_count',
 'totw_appearances',
 'starts',
 'tackles',
 'tackles_won',
 'tackles_won_pct',
 'interceptions',
 'clearances',
 'blocked_shots',
 'outfield_blocks',
 'errors_leading_to_goal',
 'errors_leading_to_shot',
 'dribbled_past',
 'aerials_won',
 'aerials_won_pct',
 'aerials_lost',
 'dribbles_completed',
 'dribbles_pct',
 'dribbles_attempted',
 'ground_duels_won',
 'ground_duels_won_pct',
 'duels_won',
 'duels_won_pct',
 'duels_lost',
 'passes_total',
 'passes_completed',
 'passes_inaccurate',
 'pass_completion_pct',
 'passes_final_third',
 'passes_opp_half',
 'passes_own_half',
 'passes_opp_half_total',
 'passes_own_half_total',
 'long_balls_total',
 'long_balls_completed',
 'long_balls_pct',
 'crosses_total',
 'crosses_completed',
 'crosses_pct',
 'chipped_passes_total',
 'chipped_passes_completed',
 'pass_to_assist',
 'attempt_assists',
 'big_chances_created',
 'big_chances_missed',
 'goals_inside_box',
 'goals_outside_box',
 'goals_headed',
 'goals_left_foot',
 'goals_right_foot',
 'goals_penalty',
 'goals_freekick',
 'own_goals',
 'goals_assists',
 'hit_woodwork',
 'shots_inside_box',
 'shots_outside_box',
 'shots_on_target',
 'shots_off_target',
 'shots_set_piece',
 'goal_conversion_pct',
 'scoring_frequency',
 'set_piece_conversion',
 'touches',
 'possession_lost',
 'possession_won_att_third',
 'dispossessed',
 'ball_recoveries',
 'fouls',
 'fouled',
 'offsides',
 'yellow_red_cards',
 'direct_red_cards',
 'pens_taken',
 'pens_conceded',
 'pens_won',
 'pen_conversion_pct',
 'pen_miss',
 'pen_post',
 'pen_on_target',
 'saves',
 'saves_caught',
 'saves_parried',
 'saves_inside_box',
 'saves_outside_box',
 'goals_conceded',
 'goals_conceded_inside_box',
 'goals_conceded_outside_box',
 'goals_prevented',
 'clean_sheets',
 'high_claims',
 'crosses_not_claimed',
 'punches',
 'runs_out',
 'runs_out_successful',
 'goal_kicks',
 'pens_saved',
 'pens_faced',
 '_ss_merge_failed',
 'is_season_total',
 '_name_norm',
 'passes_opp_half_pct',
 'passes_own_half_pct',
 'chipped_passes_pct',
 'shots_inside_box_conversion_pct',
 'shots_outside_box_conversion_pct',
 'xg_source',
 'xag_source',
 'goals_per90',
 'assists_per90',
 'npg_per90',
 'xg_per90',
 'xag_per90',
 'npxg_per90',
 'xg_chain_per90',
 'xg_buildup_per90',
 'shots_per90',
 'key_passes_per90',
 'tackles_won_per90',
 'interceptions_per90',
 'big_chances_created_per90',
 'dribbles_per90',
 'xg_overperformance',
 'npxg_overperformance']

In [45]:
df.head()

,understat_id,player,team,pos,games,minutes,goals,assists,shots,key_passes,...,xg_chain_per90,xg_buildup_per90,shots_per90,key_passes_per90,tackles_won_per90,interceptions_per90,big_chances_created_per90,dribbles_per90,xg_overperformance,npxg_overperformance
0,11295.0,David Datro Fofana,"1. FC Union Berlin,Burnley,Union Berlin",F S,31,1758,6,1,53,18,...,0.496,0.068,2.714,0.922,0.666,0.051,0.154,1.997,-2.99,-3.09
1,3699.0,Aissa Laidouni,"1. FC Union Berlin,Union Berlin",M S,29,1305,0,4,15,15,...,0.334,0.208,1.034,1.034,1.172,0.897,0.276,1.103,-0.98,-0.77
2,8017.0,Alex Kral,"1. FC Union Berlin,Union Berlin",D M S,30,1587,1,1,21,7,...,0.266,0.173,1.191,0.397,1.021,0.737,0.113,0.340,-0.78,-1.72
3,11236.0,Aljoscha Kemlein,"1. FC Union Berlin,Union Berlin",S,3,36,0,0,1,0,...,1.686,1.604,2.500,0.000,0.000,0.000,0.000,2.500,-0.03,-0.03
4,10751.0,Brenden Aaronson,"1. FC Union Berlin,Union Berlin",F M S,36,1337,2,2,22,22,...,0.500,0.226,1.480,1.480,1.211,0.336,0.269,2.355,-0.86,-0.38

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22297 entries, 0 to 22296
Columns: 149 entries, understat_id to npxg_overperformance
dtypes: bool(2), float64(131), int64(8), str(8)
memory usage: 25.0 MB

In [47]:
df["season"].value_counts().sort_index()

season
2023-2024    7209
2024-2025    7510
2025-2026    7578
Name: count, dtype: int64

In [48]:
df["league"].value_counts()

league
All Competitions            3361
UEFA Europa League          2740
UEFA Champions League       2477
England EFL Championship    2189
Spain La Liga               1783
Italy Serie A               1775
England Premier League      1668
Portugal Primeira Liga      1645
France Ligue 1              1618
Netherlands Eredivisie      1567
Germany Bundesliga          1474
Name: count, dtype: int64

In [49]:
df.groupby(["season", "league"]).size()

season     league
2023-2024  All Competitions            1070
           England EFL Championship     705
           England Premier League       569
           France Ligue 1               523
           Germany Bundesliga           494
           Italy Serie A                590
           Netherlands Eredivisie       516
           Portugal Primeira Liga       516
           Spain La Liga                596
           UEFA Champions League        721
           UEFA Europa League           909
2024-2025  All Competitions            1131
           England EFL Championship     736
           England Premier League       562
           France Ligue 1               542
           Germany Bundesliga           481
           Italy Serie A                599
           Netherlands Eredivisie       520
           Portugal Primeira Liga       562
           Spain La Liga                588
           UEFA Champions League        878
           UEFA Europa League           911
2025-2026  All Competitions            1160
           England EFL Championship     748
           England Premier League       537
           France Ligue 1               553
           Germany Bundesliga           499
           Italy Serie A                586
           Netherlands Eredivisie       531
           Portugal Primeira Liga       567
           Spain La Liga                599
           UEFA Champions League        878
           UEFA Europa League           920
dtype: int64

In [50]:
df["pos"].value_counts()

pos
D S        2419
M S        2144
F M S      1493
S          1121
D M S       898
F S         897
GK          631
D           455
D F M S     254
M           148
GK S        107
D M          58
F M          52
F            39
D F S        12
D F M         8
Name: count, dtype: int64

In [51]:
df["is_season_total"].value_counts(dropna=False)

is_season_total
False    18936
True      3361
Name: count, dtype: int64

In [52]:
df.groupby(["player", "season"]).size().describe()

count    15754.000000
mean         1.415323
std          0.821440
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          6.000000
dtype: float64

In [53]:
df[df["is_season_total"] == True][
    ["player", "team", "league", "season", "games", "minutes"]
].head(20)

,player,team,league,season,games,minutes
0,David Datro Fofana,"1. FC Union Berlin,Burnley,Union Berlin",All Competitions,2023-2024,31,1758
1,Aissa Laidouni,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,29,1305
2,Alex Kral,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,30,1587
3,Aljoscha Kemlein,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,3,36
4,Brenden Aaronson,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,36,1337
5,Christopher Trimmel,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,29,1804
6,Danilho Doekhi,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,27,2420
7,Diogo Leite,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,38,3250
8,Frederik Rönnow,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,39,3510
9,Janik Haberer,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,26,1588
10,Josip Juranovic,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,26,1688
11,Jérôme Roussillon,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,27,973
12,Kevin Volland,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,31,1627
13,Leonardo Bonucci,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,10,727
14,Lucas Tousart,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,28,1829
15,Paul Jäckel,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,9,391
16,Rani Khedira,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,24,1670
17,Robin Gosens,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,36,2795
18,Robin Knoche,"1. FC Union Berlin,Union Berlin",All Competitions,2023-2024,27,2190
19,Kevin Behrens,"1. FC Union Berlin,Union Berlin,Wolfsburg",All Competitions,2023-2024,36,2217

In [54]:
df[df["is_season_total"] == False][
    ["player", "team", "league", "season", "games", "minutes"]
].head(20)

,player,team,league,season,games,minutes
3361,Alex Pritchard,Birmingham City,England EFL Championship,2023-2024,32,1455
3362,Andre Dozzell,Birmingham City,England EFL Championship,2023-2024,35,2613
3363,Brandon Khela,Birmingham City,England EFL Championship,2023-2024,1,9
3364,Cody Drameh,Birmingham City,England EFL Championship,2023-2024,29,2273
3365,Dion Sanderson,Birmingham City,England EFL Championship,2023-2024,37,3301
3366,Emanuel Aiwu,Birmingham City,England EFL Championship,2023-2024,24,1957
3367,Emmanuel Longelo,Birmingham City,England EFL Championship,2023-2024,17,1025
3368,Ethan Laird,Birmingham City,England EFL Championship,2023-2024,25,2001
3369,Gary Gardner,Birmingham City,England EFL Championship,2023-2024,16,248
3370,George Hall,Birmingham City,England EFL Championship,2023-2024,8,150
3371,Ivan Šunjić,Birmingham City,England EFL Championship,2023-2024,36,2642
3372,Jay Stansfield,Birmingham City,England EFL Championship,2023-2024,43,3353
3373,John Ruddy,Birmingham City,England EFL Championship,2023-2024,44,3960
3374,Jordan James,Birmingham City,England EFL Championship,2023-2024,42,2347
3375,Juninho Bacuna,Birmingham City,England EFL Championship,2023-2024,45,2981
3376,Keshi Anderson,Birmingham City,England EFL Championship,2023-2024,20,1023
3377,Kevin Long,Birmingham City,England EFL Championship,2023-2024,17,1450
3378,Koji Miyoshi,Birmingham City,England EFL Championship,2023-2024,43,2522
3379,Krystian Bielik,Birmingham City,England EFL Championship,2023-2024,36,2987
3380,Lee Buchanan,Birmingham City,England EFL Championship,2023-2024,32,2733

In [55]:
df_total = df[df["is_season_total"] == True].copy()

df_total.groupby("season")["player"].nunique()

season
2023-2024    1069
2024-2025    1131
2025-2026    1160
Name: player, dtype: int64

In [56]:
jugadores_total = set(
    df[df["is_season_total"] == True]["player"]
)

jugadores_competiciones = set(
    df[df["is_season_total"] == False]["player"]
)

jugadores_sin_total = jugadores_competiciones - jugadores_total

len(jugadores_sin_total)

6463